use super::{Model, Tile};

pub fn map() -> [[Tile; 16]; 12] {
    let map = {
        [
            [
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
            ],
            [
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
            ],
            [
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
            ],
            [
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
            ],
            [
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
            ],
            [
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
            ],
            [
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
            ],
            [
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
            ],
            [
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
            ],
            [
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
            ],
            [
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
                Tile::new(1, Model::Floor),
            ],
            [
                Tile::new(0, Model::Wall),
                Tile::new(0, Model::Wall),
                Tile::new(0, Model::Wall),
                Tile::new(0, Model::Wall),
                Tile::new(0, Model::Wall),
                Tile::new(0, Model::Wall),
                Tile::new(0, Model::Wall),
                Tile::new(0, Model::Wall),
                Tile::new(0, Model::Wall),
                Tile::new(0, Model::Wall),
                Tile::new(0, Model::Wall),
                Tile::new(0, Model::Wall),
                Tile::new(0, Model::Wall),
                Tile::new(0, Model::Wall),
                Tile::new(0, Model::Wall),
                Tile::new(0, Model::Corner),
            ],
        ]
    };
    map
}
